name: Deploy Thrum AI
on:
  push:
    branches: ["main"] # Pokud máte hlavní větev pojmenovanou jinak (třeba master), změňte to

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Vložení API klíče do script.js
        run: |
          # Tento příkaz najde SECRET_PLACEHOLDER a nahradí ho vaším tajným klíčem
          sed -i "s/SECRET_PLACEHOLDER/${{ secrets.ZENTRIX_AI_API }}/g" script.js

      - name: Deploy na GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Složka s webem
          branch: gh-pages # Automat vytvoří tuto větev pro běžící web
          
